version: 0.2
env:
  variables:
    APP_NAME: "mobileapp"
    VERSION: "0.0.8"
phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing Android Studio"
      - add-apt-repository --yes ppa:maarten-fonville/android-studio
      - apt update
      - apt install android-sdk -y
      - wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip
      - unzip commandlinetools-linux-10406996_latest.zip -d cmdline-tools
      - export ANDROID_HOME=/usr/lib/android-sdk
      - export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools
      - mkdir --parents "$ANDROID_HOME/cmdline-tools/latest"
      - mv cmdline-tools/cmdline-tools/* "$ANDROID_HOME/cmdline-tools/latest/"
      - export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
      - yes | /usr/lib/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
  build:
    commands:
      - echo starting unit tests gradlew test
      - echo build process started now
      - ./gradlew assembleDebug
  post_build:
    commands:
      - echo build process finished, uploading to S3
      - mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/app-debug-$VERSION.apk
artifacts:
  files:
    - app/build/outputs/apk/debug/app-debug-$VERSION.apk
  discard-paths: yes